# Generated by Django 5.1.3 on 2024-11-13 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('dni', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=60)),
                ('mail', models.EmailField(max_length=254)),
                ('nacimiento', models.DateField()),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('codigo_postal', models.IntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='turnosApp.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=150)),
                ('apertura', models.TimeField()),
                ('cierre', models.TimeField()),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negocios', to='turnosApp.negocio')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.FloatField()),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='turnosApp.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='Prestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apertura', models.TimeField()),
                ('cierre', models.TimeField()),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestadores', to='turnosApp.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negocios_res', to='turnosApp.negocio')),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestadores_res', to='turnosApp.prestador')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_res', to='turnosApp.servicio')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales_res', to='turnosApp.sucursal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_res', to='turnosApp.usuario')),
            ],
        ),
    ]
