# Generated by Django 5.1.3 on 2025-01-31 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Bussines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('image', models.ImageField(default='bussimes_pic/default.jpg', upload_to='bussines_pic')),
                ('codigo_postal', models.IntegerField()),
                ('direccion', models.CharField(max_length=150)),
                ('latitud', models.FloatField(default=0)),
                ('longitud', models.FloatField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bussines', to='turnosApp.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Prestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apertura', models.TimeField()),
                ('cierre', models.TimeField()),
                ('bussines', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestadores', to='turnosApp.bussines')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.FloatField()),
                ('bussines', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='turnosApp.bussines')),
                ('prestadores', models.ManyToManyField(related_name='servicios', to='turnosApp.prestador')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('nota', models.CharField(blank=True, max_length=200, null=True)),
                ('bussines', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='turnosApp.bussines')),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reser_prestador', to='turnosApp.prestador')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reser_usuario', to=settings.AUTH_USER_MODEL)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reser_servicio', to='turnosApp.servicio')),
            ],
            options={
                'ordering': ['fecha', 'hora'],
                'constraints': [models.UniqueConstraint(fields=('bussines', 'prestador', 'fecha', 'hora'), name='unique_time')],
            },
        ),
    ]
