# Generated by Django 5.1.3 on 2025-01-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnosApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bussines',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bussines_pic'),
        ),
    ]
