# Generated by Django 5.1.3 on 2024-11-13 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnosApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='negocio',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='sucursal',
        ),
        migrations.AddField(
            model_name='reserva',
            name='nota',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_res', to='turnosApp.usuario'),
        ),
    ]
