# Generated by Django 5.1.3 on 2025-01-09 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnosApp', '0002_bussines_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bussines',
            name='image',
            field=models.ImageField(default='bussimes_pic/default.jpg', upload_to='bussines_pic'),
        ),
    ]
