# Generated by Django 5.1.3 on 2025-03-06 01:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnosApp', '0002_favoritos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bussines',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
