# Generated by Django 5.1.3 on 2025-03-06 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnosApp', '0003_alter_bussines_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bussines',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
