# Generated by Django 5.1.3 on 2025-01-12 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnosApp', '0003_alter_bussines_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bussines',
            name='latitud',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bussines',
            name='longitud',
            field=models.FloatField(default=0),
        ),
    ]
