# Generated by Django 5.1.3 on 2025-01-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnosApp', '0004_bussines_latitud_bussines_longitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='prestadores',
            field=models.ManyToManyField(related_name='servicios', to='turnosApp.prestador'),
        ),
    ]
