# Generated by Django 5.1.3 on 2025-01-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnosApp', '0005_servicio_prestadores'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(fields=('bussines', 'prestador', 'fecha', 'hora'), name='unique_time'),
        ),
    ]
