# Generated by Django 5.1.3 on 2025-01-28 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnosApp', '0006_reserva_unique_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['fecha', 'hora']},
        ),
    ]
