# Generated by Django 5.1.3 on 2025-03-03 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_emailconfirmationtoken_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmationtoken',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='email'),
        ),
    ]
